[workspace]

members = [
    "src/js_token",
    "src/js_lexer",
    "src/js_ast",
    "src/js_parser",
    "src/js_printer",
    "src/bundler",
    "src/source",
    "src/fs",
    "src/cli",
    "src/logger",
]
