[package]
name = "js_ast_next"
version = "0.1.0"
authors = ["Jacob Jonsson <jacobjjonsson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
span = { path = "../span" }
