name: CI

on: [push]

jobs:
    fmt:
        name: fmt
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install rustfmt
              run: rustup component add rustfmt
            - name: Run cargo fmt
              run: cargo fmt --all -- --check

    build:
        name: test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: cargo build
            - run: cargo test
